---
- name: Install Docker
  hosts: localhost
  remote_user: pi
  become: True
  vars:
    arch_mapping: # Map ansible architecture {{ ansible_architecture }} names to Docker's architecture names
      x86_64: amd64
      aarch64: arm64
  tags:
    - Install
    - Docker
  tasks:
    - name: Update and upgrade all packages to the latest version
      ansible.builtin.apt:
        update_cache: True
        upgrade: dist
        cache_valid_time: 3600

    - name: Install required packages
      ansible.builtin.apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - software-properties-common

    - name: Create directory for Docker's GPG key
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Add Docker's official GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/debian/gpg
        keyring: /etc/apt/keyrings/docker.gpg
        state: present

    - name: Print architecture variables
      ansible.builtin.debug:
        msg: 'Architecture: {{ ansible_architecture }}, Codename: {{ ansible_lsb.codename }}'

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: >-
          deb [arch={{ arch_mapping[ansible_architecture] | default(ansible_architecture) }}
          signed-by=/etc/apt/keyrings/docker.gpg]
          https://download.docker.com/linux/debian {{ ansible_lsb.codename }} stable
        filename: docker
        state: present

    - name: Install Docker and related packages
      ansible.builtin.apt:
        name: '{{ item }}'
        state: present
        update_cache: True
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin

    - name: Add Docker group
      ansible.builtin.group:
        name: docker
        state: present

    - name: Add user to Docker group
      ansible.builtin.user:
        name: '{{ ansible_user }}'
        groups: docker
        append: True

    - name: Enable and start Docker services
      ansible.builtin.systemd:
        name: '{{ item }}'
        enabled: True
        state: started
      loop:
        - docker.service
        - containerd.service

- name: Install H1ve
  hosts: localhost
  remote_user: pi
  become: True
  tags:
    - Install
    - H1ve
  vars:
    ansible_common_remote_group: docker
    h1ve_layers:
      - core
      - data
      - db
      - net
    h1ve_data: /srv/h1ve
    h1ve_config: /home/pi/.h1ve
  tasks:
    - name: H1ve email
      ansible.builtin.pause:
        prompt: Please enter your email
      register: h1ve_email

    - name: H1ve data
      ansible.builtin.pause:
        prompt: Please enter the data path ({{ h1ve_data }})
      register: h1ve_data_user

    - name: H1ve config
      ansible.builtin.pause:
        prompt: Please enter the config path ({{ h1ve_config }})
      register: h1ve_config_user

    - name: Setup environment
      ansible.builtin.copy:
        content: |
          H1VE_EMAIL={{ h1ve_email }}
          H1VE_DATA={{ h1ve_data_user if h1ve_data_user else h1ve_data }}
          H1VE_CONFIG={{ h1ve_config_user if h1ve_config_user else h1ve_config }}
        dest: '{{ playbook_dir }}/.env'
        owner: '{{ ansible_user }}'
        group: '{{ ansible_user }}'
        mode: '0644'

    - name: Create network
      community.docker.docker_network:
        name: h1ve

    - name: Generate docker-compose.yml
      include_role:
        name: h1ve
        tasks_from: generate.yml
      loop: '{{ h1ve_layers }}'
      loop_control:
        loop_var: layer_name

    - name: Start H1ve
      community.docker.docker_compose_v2:
        project_src: '{{ playbook_dir }}/src/{{ item }}'
        env_files:
          - '{{ playbook_dir }}/.env'
      loop: '{{ h1ve_layers }}'
      register: output
