- name: Include h1ve.yml
  ansible.builtin.include_vars:
    file: '{{ playbook_dir }}/src/{{ layer_name }}/h1ve.yml'
    name: layer

- name: Create docker-compose.yml
  ansible.builtin.template:
    src: '{{ playbook_dir }}/src/core/app/docker-compose.yml.j2'
    dest: '{{ playbook_dir }}/src/{{ layer_name }}/docker-compose.yml'
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    mode: '0644'
