- name: 'Store secret for {{ layer_name }}'
  ansible.builtin.copy:
    content: '{{ secret }}'
    dest: '{{ h1ve_config }}/.secrets/{{ item }}'
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    force: no
    mode: '0600'
  vars:
    secret: "{{ lookup('ansible.builtin.password', '/dev/null length=8 chars=ascii_letters') }}"
  loop: "{{ service['secrets'] }}"
  when: service['secrets'] is defined
