name: Build Docker Image

on:
  workflow_dispatch:
  push: { branches: ['docker'] }

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }} ## GitHub organization or username
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./src/h1ve/docker
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
          platforms: linux/arm64,linux/amd64
          file: ./src/h1ve/docker/Dockerfile
